# Generated by Django 4.1.3 on 2023-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_content', models.CharField(max_length=255)),
                ('blog_author', models.CharField(max_length=50)),
                ('blog_created', models.DateTimeField(auto_now_add=True)),
                ('blog_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
