# Generated by Django 4.1.3 on 2023-01-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_tests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='tests',
        ),
    ]
