# Generated by Django 4.1.3 on 2023-02-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reservation', '0003_delete_blogs_delete_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('reservationID', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('downpayment', models.DecimalField(decimal_places=3, max_digits=10)),
                ('totalPayment', models.DecimalField(decimal_places=3, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(max_length=3)),
            ],
        ),
    ]
