# Generated by Django 4.1.3 on 2023-02-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0005_customer_discount_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='facilityDescription',
            field=models.CharField(default='Error Please Contact Technical Staff', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='facilitymax',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.TimeField(auto_created=True),
        ),
    ]
