# Generated by Django 4.1.3 on 2023-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0006_customer_email_facility_facilitydescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.TimeField(auto_created=True, null=True),
        ),
    ]
