# Generated by Django 4.1.3 on 2023-02-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0007_alter_reservations_date_alter_reservations_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facilityPic',
            field=models.ImageField(null=True, upload_to='facilities'),
        ),
    ]
