# Generated by Django 4.1.3 on 2023-02-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0009_facility_facilityactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facilityPrice',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
