# Generated by Django 4.1.3 on 2023-02-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0010_alter_facility_facilityprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facilityCategory',
            field=models.CharField(choices=[('pool', 'Pool'), ('rooms', 'Rooms'), ('cottages', 'Cottages'), ('EH', 'Event Hall')], default='pool', max_length=20),
            preserve_default=False,
        ),
    ]
