# Generated by Django 4.1.3 on 2023-02-18 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0012_alter_discount_discountpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reservation.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservations',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reservation.discount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservations',
            name='facility',
            field=models.ManyToManyField(to='Reservation.facility'),
        ),
    ]
