# Generated by Django 4.1.3 on 2023-02-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0013_reservations_customer_reservations_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discountExpiration',
        ),
        migrations.AddField(
            model_name='discount',
            name='discountActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facilityCategory',
            field=models.CharField(choices=[('pool', 'Pool'), ('rooms', 'Rooms'), ('cottages', 'Cottages'), ('EH', 'Event Hall')], default='pool', max_length=20),
        ),
    ]
