# Generated by Django 4.1.3 on 2023-02-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0014_remove_discount_discountexpiration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxPax', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dayTime', models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('whole', 'Whole Day')], max_length=150)),
            ],
        ),
    ]
