# Generated by Django 4.1.3 on 2023-02-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0015_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='prices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reservation.prices'),
            preserve_default=False,
        ),
    ]
