# Generated by Django 4.1.3 on 2023-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0016_reservations_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
