# Generated by Django 4.1.3 on 2023-02-26 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0017_remove_reservations_discounted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discountPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservations',
            name='referenceNum',
            field=models.CharField(max_length=247, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='dayTime',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Whole Day', 'Whole Day')], max_length=150),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reservation.customer'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservations',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reservation.discount'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.TimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
