# Generated by Django 4.1.3 on 2023-02-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0018_remove_discount_discountpercentage_and_more'),
    ]

    operations = [
       
    ]
