# Generated by Django 4.1.3 on 2023-02-26 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0019_remove_discount_discountpercentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='timeIn',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservations',
            name='timeOut',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
