# Generated by Django 4.1.3 on 2023-02-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0021_remove_discount_discountpercentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
