# Generated by Django 4.1.3 on 2023-02-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0022_remove_discount_discountpercentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discountPercentage',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='discounted',
        ),
    ]
