# Generated by Django 4.1.4 on 2023-03-04 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0023_remove_discount_discountpercentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.TimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
