# Generated by Django 4.1.3 on 2023-02-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_content', models.CharField(max_length=255)),
                ('blog_created', models.DateTimeField(auto_now_add=True)),
                ('blog_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
