# Generated by Django 4.1.3 on 2023-02-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_blog_created_alter_blog_blog_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(null=True, upload_to='blog_pic'),
        ),
    ]
