# Generated by Django 4.1.3 on 2023-02-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_blog_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryTitle', models.CharField(max_length=255)),
                ('galleryPic', models.ImageField(upload_to='gallery')),
                ('galleryTag', models.CharField(max_length=100)),
            ],
        ),
    ]
