# Generated by Django 4.1.3 on 2023-03-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_status',
            field=models.BooleanField(default=False),
        ),
    ]
