# Generated by Django 4.1.3 on 2023-03-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthReport',
            fields=[
                ('month_report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_month', models.DateField(auto_now_add=True)),
                ('total_reservations', models.IntegerField()),
                ('total_customers', models.IntegerField()),
                ('total_earnings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeekReport',
            fields=[
                ('week_report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('reservations', models.IntegerField()),
                ('customers', models.IntegerField()),
                ('earnings', models.IntegerField()),
            ],
        ),
    ]
